package com.workintech.aaaaaaaaaaaaaaaaa;

public enum Genre {
    SCIENCE_FICTION, FANTASY, MYSTERY, THRILLER, HORROR, ROMANCE, ADVENTURE, WESTERN, BIOGRAPHY, AUTOBIOGRAPHY, HISTORY, PHILOSOPHY, PSYCHOLOGY, EPIC, TRAGEDY, COMEDY, CHILDREN, COMICS, SCIENCE, MATHEMATICS, EDUCATION, TECHNOLOGY, ART, ECONOMICS, POLITICS;
}
